(add-to-list 'load-path "~/.emacs.d/lisp")
(require 'load-path)
(require 'basic)
(require 'mirrorlist)
(require 'packages)
(require 'themes)
(require 'functions)
(require 'keymaps)
(require 'evil-keymaps)
(require 'locations)
(provide 'init)
;;;你说的对，但“原神”是一款由
