;(global-set-key (kbd "C-j") nil)
;(global-set-key (kbd "C-k") nil)
;(global-set-key (kbd "C-h") nil)
;(global-set-key (kbd "C-l") nil)
(global-set-key (kbd "C-s") 'save-buffer)
(global-set-key (kbd "<f5>") 'quickrun)
(global-set-key (kbd "C-<backspace>") 'evil-delete-backward-word)
;(global-set-key (kbd "C-backspace") ')
;(global-set-key (kbd "C-o") 'ace-window)
;(define-key 'quickrun--mode-map (kbd "<escape>") (kbd "C-x 0") )
(provide 'keymaps)
